import type {
  ClientLogo,
  NavLink,
  Service,
  CaseStudy,
  SocialLink,
  TeamMember,
  Testimonial,
} from "@/types";

// Navigation Links
export const NAVIGATION_LINKS: NavLink[] = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/blog", label: "Blog" },
  { href: "/work", label: "Work" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
] as const;

// Social Media Links
export const SOCIAL_LINKS: SocialLink[] = [
  { platform: "instagram", url: "https://www.instagram.com/nextlevelmarketerzofficial/", icon: "instagram" },
  { platform: "facebook", url: "https://www.facebook.com/nextlevelmarketerzofficial", icon: "facebook" },
] as const;

// Footer Links
export const FOOTER_LINKS = {
  company: [
    { href: "/about", label: "About Us" },
    { href: "/work", label: "Case Studies" },
    { href: "/blog", label: "Blog" },
    { href: "/contact", label: "Contact" },
  ],
  services: [
    { href: "/services/web-development", label: "Web Development" },
    { href: "/services/seo", label: "SEO Services" },
    { href: "/services/social-media-marketing", label: "Social Media Marketing" },
    { href: "/services/google-ads", label: "Google Ads" },
    { href: "/services/facebook-ads", label: "Meta Ads" },
    { href: "/services/linkedin-lead-gen", label: "Lead Generation" },
  ],
  industries: [
    { href: "/seo-for-restaurants-dubai", label: "SEO for Restaurants" },
    { href: "/seo-for-clinics-uae", label: "SEO for Clinics" },
    { href: "/seo-for-real-estate-dubai", label: "SEO for Real Estate" },
    { href: "/restaurant-website-dubai", label: "Restaurant Websites" },
    { href: "/clinic-website-design-uae", label: "Clinic Websites" },
    { href: "/ecommerce-website-dubai", label: "E-Commerce Dubai" },
  ],
  legal: [
    { href: "/privacy", label: "Privacy Policy" },
    { href: "/terms", label: "Terms of Service" },
  ],
} as const;

// Service Category to Slug Mapping for Mega Menu Navigation
export const SERVICE_SLUG_MAP: Record<string, string> = {
  // Digital Marketing
  "Search Engine Optimization (SEO)": "seo",
  "Social Media Marketing": "social-media-marketing",
  "Social Media": "social-media-marketing",
  "Influencer Marketing": "influencer-marketing",
  "PR & Outreach": "pr-outreach",
  "Email Marketing": "email-marketing",
  "Amazon Marketing": "amazon-marketing",
  "E-Commerce Marketplace": "ecommerce-marketplace",
  "SMS Marketing": "sms-marketing",
  "Video Marketing": "video-production",
  // Web & App Development
  "Web Development": "web-development",
  "Mobile App Development": "mobile-app-development",
  "Website Hosting": "website-hosting",
  "WhatsApp Business API": "whatsapp-api",
  "ZOHO": "zoho-integration",
  "AI Chatbots & Automation": "ai-chatbots",
  // Design Agency
  "Website Design Figma": "website-design",
  "Mobile App Design": "mobile-app-design",
  "Graphic Design": "graphic-design",
  "Branding": "branding",
  // Paid Media
  "Paid Media": "google-ads",
  "Google Ads": "google-ads",
  "Facebook Ads": "facebook-ads",
  "Instagram Ads": "instagram-ads",
  "Snapchat Ads": "snapchat-ads",
  "X Ads": "x-ads",
  "Reddit Ads": "reddit-ads",
  "Pinterest Ads": "pinterest-ads",
  "Linkedin Ads": "linkedin-ads",
  "TikTok Ads": "tiktok-ads",
  "Youtube Ads": "youtube-ads",
  // Lead Generation
  "LinkedIn": "linkedin-lead-gen",
  "Lead Generation": "linkedin-lead-gen",
  "Hospital": "hospital-marketing",
  "Beauty And Wellness Center": "beauty-wellness-marketing",
  "Medical Clinics": "medical-clinic-marketing",
  "Hotels": "hotel-marketing",
  "Restaurants And Bars": "restaurant-marketing",
  "B2B Companies": "b2b-lead-generation",
  "Real Estate": "real-estate-marketing",
  "School And Colleges": "education-marketing",
  "Skills And Training Center": "training-center-marketing",
  "Insurance Industries": "insurance-marketing",
  "Fintech": "fintech-marketing",
  "IT Industries": "it-marketing",
  "Security Industries": "security-marketing",
  // Video Production
  "Corporate Video Production": "corporate-video",
  "3D Video Production": "3d-video-production",
  "SaaS Explainer Video Production": "saas-explainer-video",
  "Financial Video Production": "financial-video",
  "Social Video Production": "social-video",
  "Motion Graphic Videos": "motion-graphics",
  "Video Production": "corporate-video",
  // Explainer Videos
  "Corporate Explainer Videos": "corporate-explainer",
  "B2B Explainer Videos": "b2b-explainer",
  "Tech Explainer Videos": "tech-explainer",
  "Explainer Video Production": "corporate-explainer",
  // Animated Videos
  "3D Animated CGI": "3d-animation",
  "Product Videos": "product-videos",
  "2D Animated Videos": "2d-animation",
  "Animated Videos": "3d-animation",
  // Events
  "Exhibition Stand": "exhibition-stand",
  "Events": "exhibition-stand",
} as const;

// Core Featured Services (for main showcase)
export const SERVICES: Service[] = [
  {
    id: "1",
    slug: "seo",
    title: "Search Engine Optimization",
    icon: "search",
    shortDescription: "Dominate search rankings with our proven white-hat SEO strategies.",
    description: "Our comprehensive SEO services help your business achieve top rankings on Google and other search engines. We combine technical excellence with content strategy to deliver sustainable, long-term results that drive organic traffic and qualified leads.",
    features: [
      "Technical SEO audits with detailed fix recommendations",
      "Advanced keyword research and competitor analysis",
      "On-page optimization including meta tags and structured data",
      "Quality backlink building and strategic outreach",
      "Local SEO optimization for UAE/Middle East markets",
      "Content strategy that aligns with search intent",
      "Monthly performance reports with actionable insights",
      "Mobile-first indexing optimization",
    ],
    technologies: ["Google Search Console", "SEMrush", "Ahrefs", "Screaming Frog", "Google Analytics"],
    pricing: {
      name: "Monthly Retainer",
      price: "Starting from $2,000/month",
      deliverables: ["Monthly reports", "Keyword tracking dashboard", "Content calendar", "Technical SEO fixes", "Competitor analysis"],
    },
    process: [
      { title: "Audit", description: "Comprehensive technical SEO audit identifying all optimization opportunities" },
      { title: "Strategy", description: "Custom SEO roadmap based on your goals and competitive landscape" },
      { title: "Execute", description: "Implementation of on-page, technical, and content optimizations" },
      { title: "Monitor", description: "Continuous tracking, reporting, and refinement for maximum ROI" },
    ],
    stats: [
      { value: "300%", label: "Average traffic increase" },
      { value: "150+", label: "First page rankings achieved" },
      { value: "6 months", label: "Average time to significant results" },
    ],
  },
  {
    id: "2",
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    icon: "share",
    shortDescription: "Build your brand and engage your audience across all social platforms.",
    description: "Our social media marketing services help you connect with your target audience, build brand awareness, and drive conversions. We create compelling content and manage your presence across all major social platforms.",
    features: [
      "Content strategy tailored to each platform's unique audience",
      "Professional content creation including graphics and videos",
      "Community management and engagement",
      "Paid social advertising campaigns",
      "Influencer partnership coordination",
      "Social listening and reputation management",
      "Detailed analytics and performance reporting",
    ],
    technologies: ["Meta Business Suite", "Hootsuite", "Sprout Social", "Canva", "Instagram", "LinkedIn"],
    pricing: {
      name: "Monthly Retainer",
      price: "Starting from $1,500/month",
      deliverables: ["Content calendar", "Daily posting", "Community management", "Monthly reports", "Ad campaign management"],
    },
    process: [
      { title: "Discover", description: "Brand audit and audience analysis across social platforms" },
      { title: "Plan", description: "Platform-specific content strategy and posting schedule" },
      { title: "Create", description: "Production of engaging posts, stories, reels, and videos" },
      { title: "Engage", description: "Community management, comments, and message responses" },
    ],
    stats: [
      { value: "10x", label: "Engagement rate increase" },
      { value: "50+", label: "Brands successfully managed" },
      { value: "2M+", label: "Combined follower growth" },
    ],
  },
  {
    id: "3",
    slug: "web-development",
    title: "Web Development",
    icon: "code",
    shortDescription: "High-performance websites and web applications built with cutting-edge technologies.",
    description: "We build fast, scalable, and beautiful web experiences that drive results. From landing pages to complex web applications, our development team delivers solutions that exceed expectations using the latest frameworks and best practices.",
    features: [
      "Next.js 16+ for optimal performance and SEO",
      "Server-side rendering and static generation",
      "Progressive Web App (PWA) capabilities",
      "Mobile-first responsive design",
      "TypeScript for type safety and maintainability",
      "Headless CMS integration options",
      "E-commerce functionality with secure payments",
      "Advanced animations and interactive elements",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Node.js", "Prisma", "PostgreSQL"],
    pricing: {
      name: "Starting from",
      price: "$5,000",
      deliverables: ["Custom web development", "SEO optimization", "Performance tuning", "3 months support", "Source code"],
    },
    process: [
      { title: "Design", description: "UI/UX design with clickable prototypes" },
      { title: "Develop", description: "Agile development with regular updates" },
      { title: "Test", description: "Comprehensive testing across devices and browsers" },
      { title: "Launch", description: "Deployment with performance monitoring" },
    ],
    stats: [
      { value: "99.9%", label: "Uptime guarantee" },
      { value: "<3s", label: "Average load time" },
      { value: "50+", label: "Successful launches" },
    ],
  },
  {
    id: "4",
    slug: "mobile-app-development",
    title: "Mobile App Development",
    icon: "smartphone",
    shortDescription: "Native and cross-platform mobile apps that deliver exceptional user experiences.",
    description: "We build powerful mobile applications for iOS and Android that users love. Whether you need a native app for maximum performance or a cross-platform solution for faster time-to-market, our team delivers quality results.",
    features: [
      "Native iOS development with Swift",
      "Native Android development with Kotlin",
      "Cross-platform with React Native and Flutter",
      "Intuitive UI/UX design following platform guidelines",
      "Push notification integration",
      "Offline functionality and data sync",
      "Analytics and crash reporting",
      "App Store optimization and submission support",
    ],
    technologies: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase", "App Store Connect"],
    pricing: {
      name: "Starting from",
      price: "$15,000",
      deliverables: ["Mobile app development", "UI design", "Testing", "App store submission", "6 months support"],
    },
    process: [
      { title: "Concept", description: "Product discovery and feature definition" },
      { title: "Design", description: "Wireframes and high-fidelity mockups" },
      { title: "Build", description: "Development with regular sprints and demos" },
      { title: "Deploy", description: "App store submission and launch support" },
    ],
    stats: [
      { value: "30+", label: "Apps published" },
      { value: "4.8", label: "Average app store rating" },
      { value: "500K+", label: "Total downloads" },
    ],
  },
  {
    id: "5",
    slug: "graphic-design",
    title: "Graphic Design",
    icon: "palette",
    shortDescription: "Stunning visual identities and designs that capture your brand's essence.",
    description: "From logos to complete brand systems, our design team creates visuals that resonate with your audience. We believe great design is both beautiful and functional, communicating your brand values at every touchpoint.",
    features: [
      "Logo design and brand identity systems",
      "Marketing collateral and social media graphics",
      "UI/UX design for web and mobile applications",
      "Print design including brochures and packaging",
      "Brand guidelines and comprehensive style guides",
      "Presentation templates and document design",
      "Event graphics and exhibition materials",
    ],
    technologies: ["Adobe Creative Suite", "Figma", "Illustrator", "Photoshop", "InDesign", "After Effects"],
    pricing: {
      name: "Project-based",
      price: "Starting from $1,500",
      deliverables: ["Source files", "Multiple formats", "Design rationale", "Usage rights", "Revision rounds"],
    },
    process: [
      { title: "Brief", description: "Brand discovery and design requirements" },
      { title: "Concept", description: "Mood boards and initial design directions" },
      { title: "Refine", description: "Design development based on feedback" },
      { title: "Deliver", description: "Final assets and brand guidelines" },
    ],
    stats: [
      { value: "200+", label: "Brand identities created" },
      { value: "48h", label: "Average turnaround for social graphics" },
      { value: "100%", label: "Client satisfaction rate" },
    ],
  },
  {
    id: "6",
    slug: "paid-advertising",
    title: "Paid Advertising",
    icon: "megaphone",
    shortDescription: "Data-driven paid media campaigns that maximize ROI across all platforms.",
    description: "Our paid advertising experts design and manage campaigns that convert. We use advanced targeting, creative optimization, and continuous testing to ensure every dollar of your ad spend delivers maximum return on investment.",
    features: [
      "Google Ads (Search, Display, Shopping, YouTube)",
      "Meta Ads (Facebook, Instagram, WhatsApp)",
      "LinkedIn Ads for B2B lead generation",
      "TikTok, Snapchat, and Pinterest Ads",
      "Programmatic display advertising",
      "Retargeting and remarketing campaigns",
      "A/B testing of ad creatives and copy",
      "Conversion tracking and attribution modeling",
    ],
    technologies: ["Google Ads", "Meta Ads Manager", "LinkedIn Campaign Manager", "Google Analytics", "Hotjar"],
    pricing: {
      name: "Management Fee",
      price: "Starting from $1,500/month + ad spend",
      deliverables: ["Campaign setup and management", "Weekly optimization", "Monthly reports", "Conversion tracking", "Ad creative recommendations"],
    },
    process: [
      { title: "Strategy", description: "Audience definition and channel selection" },
      { title: "Setup", description: "Campaign creation with tracking implementation" },
      { title: "Optimize", description: "Continuous testing and refinement" },
      { title: "Scale", description: "Expand winning campaigns and audiences" },
    ],
    stats: [
      { value: "300%", label: "Average ROAS achieved" },
      { value: "-40%", label: "Cost per acquisition reduction" },
      { value: "$10M+", label: "Ad spend managed annually" },
    ],
  },
  {
    id: "7",
    slug: "video-production",
    title: "Video Production",
    icon: "video",
    shortDescription: "Professional video content that tells your story and captivates your audience.",
    description: "Our video production team creates stunning visual content that connects with your audience. From corporate videos to animated explainers, we handle every aspect of production from concept to final delivery.",
    features: [
      "Corporate videos and brand stories",
      "Product showcase videos",
      "3D animation and motion graphics",
      "Explainer videos (2D and 3D)",
      "Social media video content",
      "Event coverage and highlights",
      "Video editing and post-production",
      "Scriptwriting and storyboarding",
    ],
    technologies: ["Adobe Premiere", "After Effects", "Cinema 4D", "DaVinci Resolve", "Final Cut Pro"],
    pricing: {
      name: "Project-based",
      price: "Starting from $3,000",
      deliverables: ["Full HD/4K video files", "Multiple versions", "Music licensing", "Revision rounds", "Raw footage available"],
    },
    process: [
      { title: "Pre-production", description: "Concept, script, and storyboard development" },
      { title: "Production", description: "Filming or animation with professional equipment" },
      { title: "Post-production", description: "Editing, effects, color grading, and sound" },
      { title: "Delivery", description: "Final files in all required formats" },
    ],
    stats: [
      { value: "150+", label: "Videos produced" },
      { value: "4K", label: "Ultra HD quality standard" },
      { value: "2 weeks", label: "Average production timeline" },
    ],
  },
  {
    id: "8",
    slug: "lead-generation",
    title: "Lead Generation",
    icon: "users",
    shortDescription: "Strategic lead generation campaigns that fill your pipeline with qualified prospects.",
    description: "Our lead generation services combine multiple channels and strategies to attract, capture, and nurture high-quality leads for your business. We specialize in B2B lead generation across various industries.",
    features: [
      "LinkedIn lead generation campaigns",
      "Industry-specific strategies (healthcare, real estate, education)",
      "Landing page design and optimization",
      "Lead magnet creation",
      "Email nurturing sequences",
      "CRM integration and automation",
      "Lead scoring and qualification",
      "ROI tracking and reporting",
    ],
    technologies: ["LinkedIn Sales Navigator", "HubSpot", "Marketo", "Mailchimp", "Zapier"],
    pricing: {
      name: "Pay-per-lead or Retainer",
      price: "Starting from $2,000/month",
      deliverables: ["Lead generation strategy", "Campaign management", "Monthly reporting", "CRM setup", "Lead qualification"],
    },
    process: [
      { title: "Target", description: "Ideal customer profile definition" },
      { title: "Attract", description: "Multi-channel campaign execution" },
      { title: "Capture", description: "Landing page optimization and form strategy" },
      { title: "Nurture", description: "Automated email sequences and follow-up" },
    ],
    stats: [
      { value: "500+", label: "Qualified leads monthly avg" },
      { value: "35%", label: "Conversion to opportunities" },
      { value: "20+", label: "Industries served" },
    ],
  },
  {
    id: "9",
    slug: "influencer-marketing",
    title: "Influencer Marketing",
    icon: "users",
    shortDescription: "Partner with relevant influencers to amplify your brand message.",
    description: "Our influencer marketing services connect your brand with the right voices in your industry. We identify, negotiate with, and manage influencer partnerships that drive authentic engagement and conversions.",
    features: ["Influencer identification and vetting", "Campaign strategy and creative direction", "Contract negotiation and compliance", "Performance tracking and ROI analysis"],
    technologies: ["Influencer Marketing Platforms", "Social Listening Tools", "Analytics Platforms"],
    pricing: { name: "Campaign-based", price: "Starting from $5,000", deliverables: ["Influencer sourcing", "Campaign management", "Performance reports", "Content approval"] },
  },
  {
    id: "10",
    slug: "pr-outreach",
    title: "PR & Outreach",
    icon: "megaphone",
    shortDescription: "Build brand authority through strategic public relations.",
    description: "Our PR services help you build credibility and visibility through media coverage, thought leadership, and strategic communications. We craft compelling stories that resonate with your target audience.",
    features: ["Press release creation and distribution", "Media relations and outreach", "Thought leadership content", "Crisis communications"],
    technologies: ["PR Distribution Services", "Media Databases", "Monitoring Tools"],
    pricing: { name: "Monthly Retainer", price: "Starting from $3,000/month", deliverables: ["Press releases", "Media pitches", "Coverage reports", "Strategy calls"] },
  },
  {
    id: "11",
    slug: "email-marketing",
    title: "Email Marketing",
    icon: "mail",
    shortDescription: "Drive engagement and conversions with targeted email campaigns.",
    description: "Our email marketing services help you nurture leads and convert customers with personalized, data-driven campaigns. From strategy to execution, we deliver emails that get opened and acted upon.",
    features: ["Email strategy and automation", "List segmentation and personalization", "A/B testing for optimization", "Detailed analytics and reporting"],
    technologies: ["Mailchimp", "Klaviyo", "HubSpot", "ConvertKit"],
    pricing: { name: "Monthly Retainer", price: "Starting from $1,500/month", deliverables: ["Campaign management", "Template design", "Automation setup", "Performance reports"] },
  },
  {
    id: "12",
    slug: "website-hosting",
    title: "Website Hosting",
    icon: "server",
    shortDescription: "Reliable, secure, and fast hosting for your website.",
    description: "Our managed hosting services ensure your website is always fast, secure, and online. We handle everything from server setup to ongoing maintenance and security updates.",
    features: ["99.9% uptime guarantee", "Daily backups", "SSL certificates", "24/7 support", "CDN integration"],
    technologies: ["Vercel", "AWS", "Cloudflare", "Node.js"],
    pricing: { name: "Monthly", price: "Starting from $50/month", deliverables: ["Hosting", "SSL certificate", "Daily backups", "Support"] },
  },
  {
    id: "13",
    slug: "whatsapp-api",
    title: "WhatsApp Business API",
    icon: "message-circle",
    shortDescription: "Connect with customers directly on WhatsApp.",
    description: "Our WhatsApp Business API integration helps you provide customer support, send updates, and drive sales through the world's most popular messaging app.",
    features: ["API integration", "Message templates", "Automated responses", "Analytics dashboard"],
    technologies: ["WhatsApp Business API", "Twilio", "MessageBird"],
    pricing: { name: "Monthly + Usage", price: "Starting from $200/month", deliverables: ["API setup", "Template creation", "Integration", "Support"] },
  },
  {
    id: "14",
    slug: "zoho-integration",
    title: "ZOHO Integration",
    icon: "database",
    shortDescription: "Streamline operations with ZOHO business suite integration.",
    description: "Our ZOHO integration services help you automate workflows and centralize data across the ZOHO suite. From CRM to Books, we ensure all your tools work together seamlessly.",
    features: ["ZOHO CRM integration", "ZOHO Books setup", "Custom workflow automation", "Data migration"],
    technologies: ["ZOHO CRM", "ZOHO Books", "ZOHO Forms", "API Connect"],
    pricing: { name: "Project-based", price: "Starting from $2,500", deliverables: ["Integration setup", "Workflow automation", "Training", "Documentation"] },
  },
  {
    id: "15",
    slug: "website-design",
    title: "Website Design",
    icon: "figma",
    shortDescription: "Beautiful, user-centered website designs in Figma.",
    description: "Our website design services create stunning, conversion-focused designs that bring your brand to life. We design with users in mind, ensuring beautiful aesthetics meet seamless functionality.",
    features: ["UX research and personas", "Wireframing and prototyping", "High-fidelity Figma designs", "Design system creation"],
    technologies: ["Figma", "Adobe XD", "Sketch", "Principle"],
    pricing: { name: "Project-based", price: "Starting from $3,000", deliverables: ["Figma files", "Interactive prototype", "Design system", "Assets"] },
  },
  {
    id: "16",
    slug: "mobile-app-design",
    title: "Mobile App Design",
    icon: "smartphone",
    shortDescription: "Intuitive mobile app interfaces users love.",
    description: "Our mobile app design services create beautiful, intuitive interfaces for iOS and Android. We follow platform guidelines while delivering unique, brand-aligned experiences.",
    features: ["iOS and Android design", "User flow optimization", "Gesture-based interactions", "Design system"],
    technologies: ["Figma", "Sketch", "InVision", "Principle"],
    pricing: { name: "Project-based", price: "Starting from $5,000", deliverables: ["Design files", "Prototype", "Style guide", "Assets"] },
  },
  {
    id: "17",
    slug: "branding",
    title: "Branding",
    icon: "sparkles",
    shortDescription: "Complete brand identity systems that resonate.",
    description: "Our branding services create comprehensive visual and verbal identities that capture your essence and connect with your audience. From logos to guidelines, we build brands that last.",
    features: ["Logo design", "Color palette", "Typography system", "Brand guidelines", "Voice and tone"],
    technologies: ["Adobe Illustrator", "Figma", "Photoshop", "InDesign"],
    pricing: { name: "Project-based", price: "Starting from $5,000", deliverables: ["Logo files", "Brand guidelines", "Color palette", "Typography"] },
  },
  {
    id: "18",
    slug: "google-ads",
    title: "Google Ads",
    icon: "search",
    shortDescription: "Drive results with targeted Google advertising campaigns.",
    description: "Our Google Ads experts create and manage campaigns that maximize your ROI across Search, Display, Shopping, and YouTube. We focus on the campaigns that deliver the best results for your business.",
    features: ["Search campaigns", "Display advertising", "Shopping ads", "YouTube ads", "Performance max"],
    technologies: ["Google Ads", "Google Analytics", "Google Tag Manager"],
    pricing: { name: "Management Fee", price: "Starting from $1,500/month + ad spend", deliverables: ["Campaign setup", "Ongoing optimization", "Reporting", "Conversion tracking"] },
  },
  {
    id: "19",
    slug: "facebook-ads",
    title: "Facebook Ads",
    icon: "facebook",
    shortDescription: "Reach your audience with targeted Facebook advertising.",
    description: "Our Facebook Ads services help you reach and convert your ideal customers with precision targeting and compelling creatives. We manage campaigns that drive real business results.",
    features: ["Audience targeting", "A/B testing", "Creative optimization", "Remarketing campaigns"],
    technologies: ["Meta Ads Manager", "Facebook Pixel", "Analytics"],
    pricing: { name: "Management Fee", price: "Starting from $1,000/month + ad spend", deliverables: ["Campaign management", "Creative recommendations", "Reporting", "Pixel setup"] },
  },
  {
    id: "20",
    slug: "instagram-ads",
    title: "Instagram Ads",
    icon: "instagram",
    shortDescription: "Visual advertising that captures attention on Instagram.",
    description: "Our Instagram Ads services create visually stunning campaigns that stop the scroll. From Stories to Reels ads, we know what works on this visual-first platform.",
    features: ["Story ads", "Reels advertising", "Shopping integration", "Influencer collab ads"],
    technologies: ["Meta Ads Manager", "Instagram Insights", "Creative Tools"],
    pricing: { name: "Management Fee", price: "Starting from $1,000/month + ad spend", deliverables: ["Campaign management", "Creative assets", "Reporting", "Strategy"] },
  },
  {
    id: "21",
    slug: "linkedin-ads",
    title: "LinkedIn Ads",
    icon: "linkedin",
    shortDescription: "B2B advertising that reaches decision-makers.",
    description: "Our LinkedIn Ads services help you reach professionals and decision-makers with precise targeting. Perfect for B2B lead generation and brand awareness campaigns.",
    features: ["Sponsored content", "InMail campaigns", "Text ads", "Dynamic ads"],
    technologies: ["LinkedIn Campaign Manager", "LinkedIn Insight Tag"],
    pricing: { name: "Management Fee", price: "Starting from $2,000/month + ad spend", deliverables: ["Campaign management", "Targeting strategy", "Reporting", "Lead forms"] },
  },
  {
    id: "22",
    slug: "tiktok-ads",
    title: "TikTok Ads",
    icon: "video",
    shortDescription: "Reach younger audiences with viral TikTok advertising.",
    description: "Our TikTok Ads services help you tap into the massive engaged audience on this rapidly growing platform. We create authentic campaigns that feel native to TikTok.",
    features: ["In-feed ads", "TopView ads", "Spark Ads", "Branded hashtag challenges"],
    technologies: ["TikTok Ads Manager", "TikTok Creative Center"],
    pricing: { name: "Management Fee", price: "Starting from $1,500/month + ad spend", deliverables: ["Campaign setup", "Creative strategy", "Reporting", "Optimization"] },
  },
  {
    id: "23",
    slug: "youtube-ads",
    title: "YouTube Ads",
    icon: "youtube",
    shortDescription: "Video advertising that engages and converts.",
    description: "Our YouTube Ads services help you reach audiences with engaging video ads across the world's largest video platform. From skippable to non-skippable, we know what works.",
    features: ["Skippable in-stream", "Non-skippable ads", "Bumper ads", "Masthead ads"],
    technologies: ["Google Ads", "YouTube Analytics", "Google Studio"],
    pricing: { name: "Management Fee", price: "Starting from $1,500/month + ad spend", deliverables: ["Campaign management", "Video creative", "Reporting", "Optimization"] },
  },
  {
    id: "24",
    slug: "linkedin-lead-gen",
    title: "LinkedIn Lead Generation",
    icon: "linkedin",
    shortDescription: "Generate high-quality B2B leads on LinkedIn.",
    description: "Our LinkedIn lead generation services help you connect with decision-makers and fill your pipeline with qualified prospects. We use organic and paid strategies for maximum results.",
    features: ["Profile optimization", "Content strategy", "Lead generation forms", "Outreach campaigns"],
    technologies: ["LinkedIn Sales Navigator", "LinkedIn Ads", "CRM Integrations"],
    pricing: { name: "Monthly Retainer", price: "Starting from $3,000/month", deliverables: ["Lead generation", "Content creation", "Outreach", "Reporting"] },
  },
  {
    id: "25",
    slug: "hospital-marketing",
    title: "Hospital Marketing",
    icon: "heart-pulse",
    shortDescription: "Specialized marketing for hospitals and healthcare.",
    description: "Our healthcare marketing services help hospitals attract patients and build trust in their communities. We understand the unique challenges and regulations of healthcare marketing.",
    features: ["Patient acquisition", "Reputation management", "Healthcare SEO", "Content marketing"],
    technologies: ["Healthcare platforms", "Review management", "Analytics"],
    pricing: { name: "Monthly Retainer", price: "Starting from $5,000/month", deliverables: ["Marketing strategy", "Campaign management", "Reporting", "Compliance"] },
  },
  {
    id: "26",
    slug: "real-estate-marketing",
    title: "Real Estate Marketing",
    icon: "building",
    shortDescription: "Drive property sales and rentals with targeted marketing.",
    description: "Our real estate marketing services help agents and developers attract qualified buyers and renters. From listings to open houses, we cover it all.",
    features: ["Property listings optimization", "Virtual tours", "Lead nurturing", "Social media advertising"],
    technologies: ["Real Estate platforms", "Social Media", "CRM"],
    pricing: { name: "Monthly Retainer", price: "Starting from $2,500/month", deliverables: ["Marketing strategy", "Campaign management", "Lead generation", "Reporting"] },
  },
  {
    id: "27",
    slug: "education-marketing",
    title: "Education Marketing",
    icon: "graduation-cap",
    shortDescription: "Enrollment marketing for schools and colleges.",
    description: "Our education marketing services help schools and colleges attract students and build their brand. We understand the academic calendar and student decision journey.",
    features: ["Enrollment campaigns", "Virtual events", "Content marketing", "Student ambassadors"],
    technologies: ["Education platforms", "Social Media", "Analytics"],
    pricing: { name: "Monthly Retainer", price: "Starting from $3,000/month", deliverables: ["Marketing strategy", "Campaigns", "Content", "Reporting"] },
  },
  {
    id: "28",
    slug: "corporate-video",
    title: "Corporate Video Production",
    icon: "video",
    shortDescription: "Professional corporate videos that communicate your message.",
    description: "Our corporate video production services create polished, professional videos for internal and external communications. From brand stories to training videos, we deliver quality.",
    features: ["Brand videos", "Training content", "Event coverage", "Interviews"],
    technologies: ["Professional cameras", "Editing software", "Motion graphics"],
    pricing: { name: "Project-based", price: "Starting from $5,000", deliverables: ["Full production", "Editing", "Motion graphics", "Files"] },
  },
  {
    id: "29",
    slug: "3d-video-production",
    title: "3D Video Production",
    icon: "box",
    shortDescription: "Stunning 3D animated videos for products and concepts.",
    description: "Our 3D video production services create photorealistic 3D animations that showcase products and visualize concepts. Perfect for product launches and technical explanations.",
    features: ["3D modeling", "Animation", "Rendering", "Visual effects"],
    technologies: ["Cinema 4D", "Blender", "After Effects", "Octane"],
    pricing: { name: "Project-based", price: "Starting from $8,000", deliverables: ["3D animation", "Sound design", "Revisions", "Files"] },
  },
  {
    id: "30",
    slug: "motion-graphics",
    title: "Motion Graphics",
    icon: "zap",
    shortDescription: "Dynamic motion graphics for videos and social media.",
    description: "Our motion graphics services add life to your content with stunning animations. From logo reveals to explainer videos, we create visuals that captivate.",
    features: ["Logo animations", "Lower thirds", "Transitions", "Infographic animations"],
    technologies: ["After Effects", "Premiere Pro", "Cinema 4D"],
    pricing: { name: "Project-based", price: "Starting from $2,000", deliverables: ["Motion graphics", "Sound design", "Files", "Revisions"] },
  },
  {
    id: "31",
    slug: "exhibition-stand",
    title: "Exhibition Stand Design",
    icon: "layout",
    shortDescription: "Eye-catching exhibition stands that attract visitors.",
    description: "Our exhibition stand design services create memorable spaces that draw crowds at trade shows and events. We design stands that reflect your brand and facilitate engagement.",
    features: ["3D stand design", "Brand integration", "Interactive elements", "Production supervision"],
    technologies: ["3D software", "Rendering tools", "Printing partners"],
    pricing: { name: "Project-based", price: "Starting from $10,000", deliverables: ["3D designs", "Renderings", "Production files", "On-site support"] },
  },
  {
    id: "32",
    slug: "amazon-marketing",
    title: "Amazon Marketing",
    icon: "shopping-cart",
    shortDescription: "Boost your Amazon sales with optimized listings and advertising.",
    description: "Our Amazon marketing services help you increase visibility and sales on the world's largest marketplace. From SEO to advertising, we cover everything you need to succeed.",
    features: ["Product listing optimization", "Amazon SEO", "Sponsored Products ads", "Brand Registry setup", "Review management"],
    technologies: ["Amazon Advertising", "Seller Central", "Amazon Analytics"],
    pricing: { name: "Monthly Retainer", price: "Starting from $2,500/month", deliverables: ["Campaign management", "Listing optimization", "Reporting", "Strategy"] },
  },
  {
    id: "33",
    slug: "ecommerce-marketplace",
    title: "E-Commerce Marketplace",
    icon: "store",
    shortDescription: "Multi-channel marketplace management for maximum reach.",
    description: "Our e-commerce marketplace services help you sell across multiple platforms efficiently. We integrate and optimize your presence on Amazon, eBay, Walmart, and more.",
    features: ["Multi-platform integration", "Inventory sync", "Order management", "Pricing optimization", "Performance analytics"],
    technologies: ["ChannelAdvisor", "Sellbrite", "Amazon API", "eBay API"],
    pricing: { name: "Monthly Retainer", price: "Starting from $3,000/month", deliverables: ["Platform management", "Integration", "Optimization", "Reporting"] },
  },
  {
    id: "34",
    slug: "sms-marketing",
    title: "SMS Marketing",
    icon: "message-square",
    shortDescription: "Direct customer engagement through SMS campaigns.",
    description: "Our SMS marketing services deliver high-open rates and instant engagement. Perfect for promotions, reminders, and time-sensitive offers.",
    features: ["SMS campaign management", "Automation workflows", "Compliance management", "Segmentation", "Analytics"],
    technologies: ["Twilio", "MessageBird", "SMS APIs", "Analytics platforms"],
    pricing: { name: "Monthly + Usage", price: "Starting from $500/month + SMS costs", deliverables: ["Campaign setup", "Automation", "Reporting", "Compliance"] },
  },
  {
    id: "35",
    slug: "snapchat-ads",
    title: "Snapchat Ads",
    icon: "camera",
    shortDescription: "Reach younger audiences on Snapchat.",
    description: "Our Snapchat Ads services help you connect with Gen Z and younger millennials through vertical video and story ads that feel native to the platform.",
    features: ["Story ads", "AR lenses", "Collection ads", "App install ads", "Targeting options"],
    technologies: ["Snapchat Ads Manager", "Snapchat Pixel", "Creative tools"],
    pricing: { name: "Management Fee", price: "Starting from $1,000/month + ad spend", deliverables: ["Campaign management", "Creative strategy", "Reporting", "Optimization"] },
  },
  {
    id: "36",
    slug: "x-ads",
    title: "X (Twitter) Ads",
    icon: "twitter",
    shortDescription: "Amplify your message on X platform.",
    description: "Our X Ads services help you reach engaged audiences through promoted tweets, trends, and targeted advertising on the platform formerly known as Twitter.",
    features: ["Promoted tweets", "Trends sponsorship", "Follower ads", "Website conversions", "Engagement tracking"],
    technologies: ["X Ads Manager", "X Analytics", "Conversion tracking"],
    pricing: { name: "Management Fee", price: "Starting from $1,000/month + ad spend", deliverables: ["Campaign management", "Creative", "Reporting", "Optimization"] },
  },
  {
    id: "37",
    slug: "reddit-ads",
    title: "Reddit Ads",
    icon: "reddit",
    shortDescription: "Engage communities through Reddit advertising.",
    description: "Our Reddit Ads services help you reach passionate communities through targeted advertising on subreddits and across the platform.",
    features: ["Community targeting", "AMAs", "Sponsored posts", "Video ads", "Conversion tracking"],
    technologies: ["Reddit Ads", "Reddit Pixel", "Community tools"],
    pricing: { name: "Management Fee", price: "Starting from $1,200/month + ad spend", deliverables: ["Campaign management", "Strategy", "Reporting", "Creative"] },
  },
  {
    id: "38",
    slug: "pinterest-ads",
    title: "Pinterest Ads",
    icon: "pin",
    shortDescription: "Drive discovery and sales through Pinterest.",
    description: "Our Pinterest Ads services help you reach users in discovery mode, perfect for brands with visual products looking to drive sales and awareness.",
    features: ["Promoted pins", "Shopping ads", "Collection ads", "Idea ads", "Conversion tracking"],
    technologies: ["Pinterest Ads", "Pinterest Tag", "Catalog feeds"],
    pricing: { name: "Management Fee", price: "Starting from $1,000/month + ad spend", deliverables: ["Campaign management", "Feed setup", "Reporting", "Creative"] },
  },
  {
    id: "39",
    slug: "beauty-wellness-marketing",
    title: "Beauty & Wellness Marketing",
    icon: "sparkles",
    shortDescription: "Specialized marketing for beauty and wellness brands.",
    description: "Our beauty and wellness marketing services help spas, salons, and wellness centers attract clients through Instagram-worthy content and targeted advertising.",
    features: ["Instagram strategy", "Influencer partnerships", "Booking system integration", "Review management", "Seasonal campaigns"],
    technologies: ["Instagram", "TikTok", "Booking systems", "Review platforms"],
    pricing: { name: "Monthly Retainer", price: "Starting from $3,000/month", deliverables: ["Social management", "Content creation", "Ads", "Reporting"] },
  },
  {
    id: "40",
    slug: "medical-clinic-marketing",
    title: "Medical Clinic Marketing",
    icon: "activity",
    shortDescription: "Patient acquisition for medical practices.",
    description: "Our medical clinic marketing services help doctors and healthcare providers attract new patients while maintaining compliance with healthcare advertising regulations.",
    features: ["Local SEO", "Healthcare PPC", "Reputation management", "Patient reviews", "Email marketing"],
    technologies: ["Google Ads", "Healthcare directories", "Review platforms"],
    pricing: { name: "Monthly Retainer", price: "Starting from $4,000/month", deliverables: ["PPC management", "SEO", "Reviews", "Reporting"] },
  },
  {
    id: "41",
    slug: "hotel-marketing",
    title: "Hotel Marketing",
    icon: "building-2",
    shortDescription: "Drive direct bookings for hotels and resorts.",
    description: "Our hotel marketing services help properties increase direct bookings, reduce OTA dependency, and build a strong brand presence across all channels.",
    features: ["Direct booking campaigns", "Metasearch optimization", "Email marketing", "Loyalty programs", "Social media"],
    technologies: ["Google Hotel Ads", "Meta Ads", "Booking engines", "Email platforms"],
    pricing: { name: "Monthly Retainer", price: "Starting from $5,000/month", deliverables: ["Campaign management", "Email", "Social", "Reporting"] },
  },
  {
    id: "42",
    slug: "restaurant-marketing",
    title: "Restaurant & Bar Marketing",
    icon: "utensils",
    shortDescription: "Fill seats and build a loyal customer base.",
    description: "Our restaurant and bar marketing services help food venues attract diners through social media, local SEO, review management, and targeted campaigns.",
    features: ["Social media content", "Google Business optimization", "Review management", "Email campaigns", "Event promotion"],
    technologies: ["Instagram", "TikTok", "Google Business", "Reservation platforms"],
    pricing: { name: "Monthly Retainer", price: "Starting from $2,500/month", deliverables: ["Content", "Management", "Reviews", "Promotions"] },
  },
  {
    id: "43",
    slug: "insurance-marketing",
    title: "Insurance Marketing",
    icon: "shield",
    shortDescription: "Generate qualified leads for insurance providers.",
    description: "Our insurance marketing services help agents and carriers generate high-quality leads through compliant advertising and strategic content marketing.",
    features: ["Compliant lead generation", "Content marketing", "Email nurturing", "Landing pages", "CRM integration"],
    technologies: ["Google Ads", "Meta Ads", "LinkedIn", "CRM systems"],
    pricing: { name: "Per Lead or Retainer", price: "Starting from $3,000/month", deliverables: ["Lead gen", "Nurturing", "Reporting", "Compliance"] },
  },
  {
    id: "44",
    slug: "fintech-marketing",
    title: "Fintech Marketing",
    icon: "credit-card",
    shortDescription: "Growth marketing for financial technology.",
    description: "Our fintech marketing services help financial technology companies acquire users and build trust in competitive markets through performance marketing and brand building.",
    features: ["App install campaigns", "Content marketing", "Influencer partnerships", "PR & outreach", "Referral programs"],
    technologies: ["Google Ads", "Meta Ads", "LinkedIn", "AppsFlyer"],
    pricing: { name: "Monthly Retainer", price: "Starting from $5,000/month", deliverables: ["Campaigns", "Content", "Influencers", "Analytics"] },
  },
  {
    id: "45",
    slug: "it-marketing",
    title: "IT Industry Marketing",
    icon: "server",
    shortDescription: "B2B marketing for IT companies and MSPs.",
    description: "Our IT marketing services help technology companies generate leads and build authority through content, SEO, and account-based marketing.",
    features: ["Account-based marketing", "Content marketing", "LinkedIn lead gen", "Technical SEO", "Email sequences"],
    technologies: ["LinkedIn", "Google Ads", "Marketing automation", "CRM"],
    pricing: { name: "Monthly Retainer", price: "Starting from $4,000/month", deliverables: ["ABM", "Content", "LinkedIn", "Reporting"] },
  },
  {
    id: "46",
    slug: "security-marketing",
    title: "Security Industry Marketing",
    icon: "lock",
    shortDescription: "Lead generation for security services.",
    description: "Our security industry marketing services help security companies and MSPs generate qualified leads through targeted campaigns and thought leadership content.",
    features: ["Google Ads", "LinkedIn marketing", "Case studies", "Email nurturing", "Landing pages"],
    technologies: ["Google Ads", "LinkedIn", "Marketing automation"],
    pricing: { name: "Monthly Retainer", price: "Starting from $3,500/month", deliverables: ["Campaigns", "Content", "Lead gen", "Reporting"] },
  },
  {
    id: "47",
    slug: "saas-explainer-video",
    title: "SaaS Explainer Videos",
    icon: "video",
    shortDescription: "Explain your SaaS product with engaging video.",
    description: "Our SaaS explainer video services create compelling videos that explain complex software products in simple, engaging ways. Perfect for landing pages and demos.",
    features: ["Script writing", "Storyboards", "2D/3D animation", "Voiceover", "Sound design"],
    technologies: ["After Effects", "Premiere Pro", "Recording tools"],
    pricing: { name: "Project-based", price: "Starting from $5,000", deliverables: ["Full production", "Script", "Animation", "Revisions"] },
  },
  {
    id: "48",
    slug: "financial-video",
    title: "Financial Video Production",
    icon: "dollar-sign",
    shortDescription: "Professional videos for financial services.",
    description: "Our financial video production services create trust-building content for banks, investment firms, and fintech companies. From interviews to explainers, we cover it all.",
    features: ["Interviews", "Explainer videos", "Event coverage", "Documentary style", "Compliance review"],
    technologies: ["Professional cameras", "Lighting", "Editing software"],
    pricing: { name: "Project-based", price: "Starting from $7,500", deliverables: ["Full production", "Editing", "Compliance", "Files"] },
  },
  {
    id: "49",
    slug: "social-video",
    title: "Social Video Production",
    icon: "smartphone",
    shortDescription: "Platform-optimized videos for social media.",
    description: "Our social video production services create thumb-stopping content optimized for each platform's unique format and audience behavior.",
    features: ["Platform-specific formats", "Trend-based content", "Fast turnaround", "Captions", "Thumbnails"],
    technologies: ["Mobile editing", "Social platforms", "Trend tools"],
    pricing: { name: "Per video or packages", price: "Starting from $500/video", deliverables: ["Video file", "Optimization", "Captions", "Thumbnails"] },
  },
  {
    id: "50",
    slug: "corporate-explainer",
    title: "Corporate Explainer Videos",
    icon: "building",
    shortDescription: "Simplify your business message with video.",
    description: "Our corporate explainer video services help you communicate complex business ideas simply and effectively. Perfect for sales, training, and investor presentations.",
    features: ["Script development", "Animation or live-action", "Professional voiceover", "Sound design", "Multiple formats"],
    technologies: ["After Effects", "Premiere Pro", "Recording", "Studio"],
    pricing: { name: "Project-based", price: "Starting from $4,000", deliverables: ["Full production", "Script", "Voiceover", "Files"] },
  },
  {
    id: "51",
    slug: "b2b-explainer",
    title: "B2B Explainer Videos",
    icon: "briefcase",
    shortDescription: "Professional explainers for B2B audiences.",
    description: "Our B2B explainer videos are designed to communicate complex value propositions to business decision-makers clearly and persuasively.",
    features: ["Audience research", "Professional scripts", "Clean animation", "Executive approval", "Multiple versions"],
    technologies: ["Motion graphics", "Whiteboard", "Screen recording", "Voiceover"],
    pricing: { name: "Project-based", price: "Starting from $5,000", deliverables: ["Research", "Script", "Animation", "Revisions"] },
  },
  {
    id: "52",
    slug: "tech-explainer",
    title: "Tech Explainer Videos",
    icon: "cpu",
    shortDescription: "Explain technical products with clarity.",
    description: "Our tech explainer videos specialize in making complex technology accessible. Perfect for software, hardware, and technical services.",
    features: ["Technical accuracy", "UI animations", "Screen recording", "Schematic diagrams", "Code visualization"],
    technologies: ["Screen recording", "Motion graphics", "UI animation", "After Effects"],
    pricing: { name: "Project-based", price: "Starting from $6,000", deliverables: ["Script", "Animation", "Sound", "Files"] },
  },
  {
    id: "53",
    slug: "3d-animation",
    title: "3D Animated Videos",
    icon: "box",
    shortDescription: "Photorealistic 3D animation for your brand.",
    description: "Our 3D animated video services create stunning, photorealistic animations that showcase products, explain services, or tell your brand story.",
    features: ["3D modeling", "Texturing", "Lighting", "Rendering", "Animation"],
    technologies: ["Cinema 4D", "Blender", "Octane", "Redshift"],
    pricing: { name: "Project-based", price: "Starting from $8,000", deliverables: ["3D assets", "Animation", "Rendering", "Source files"] },
  },
  {
    id: "54",
    slug: "product-videos",
    title: "Product Videos",
    icon: "package",
    shortDescription: "Showcase your products with compelling video.",
    description: "Our product video services create stunning visuals that highlight features and benefits. From unboxing to demos, we make products irresistible.",
    features: ["Product showcase", "Feature highlights", "Lifestyle shots", "Multi-platform versions", "E-commerce optimized"],
    technologies: ["Professional cameras", "Lighting", "Gimbals", "Editing"],
    pricing: { name: "Project-based", price: "Starting from $3,000", deliverables: ["Footage", "Editing", "Music", "Multiple versions"] },
  },
  {
    id: "55",
    slug: "2d-animation",
    title: "2D Animated Videos",
    icon: "film",
    shortDescription: "Engaging 2D animation for any purpose.",
    description: "Our 2D animated video services create charming, effective animations for explainer videos, marketing content, educational materials, and more.",
    features: ["Custom illustration", "Character animation", "Motion graphics", "Voiceover", "Sound effects"],
    technologies: ["After Effects", "Animate", "Illustrator", "Pro Tools"],
    pricing: { name: "Project-based", price: "Starting from $4,000", deliverables: ["Animation", "Sound", "Files", "Revisions"] },
  },
  {
    id: "56",
    slug: "ai-chatbots",
    title: "AI Chatbots & Automation",
    icon: "cpu",
    shortDescription: "Custom AI chatbots and workflow automation.",
    description: "We design and build custom AI-powered chatbots and workflow automation systems that capture leads 24/7, answer customer questions instantly, and streamline your operations. Leveraging [Octively](https://octively.com), we implement RAG capabilities and custom conversational flows to elevate your business.",
    features: [
      "Custom AI chatbots with advanced RAG",
      "24/7 lead capture and qualification",
      "Process & workflow automation",
      "Chatbot analytics dashboards for key user insights",
      "Detailed conversational tracking and reporting"
    ],
    technologies: ["Octively", "Zapier", "CRMs", "APIs"],
    pricing: { name: "Project-based", price: "Starting from $2,500", deliverables: ["Chatbot deployment", "Workflow setup", "Analytics dashboard", "Support"] },
  },
] as const;

// Helper function to get service slug from service name
export function getServiceSlug(serviceName: string): string | null {
  return SERVICE_SLUG_MAP[serviceName] || null;
}

// Helper function to get service URL from service name
export function getServiceUrl(serviceName: string): string {
  const slug = getServiceSlug(serviceName);
  return slug ? `/services/${slug}` : "/contact";
}

// Expanded Services List (from user requirements for Phase 2)
export const ALL_SERVICES = [
  "Lead Generation",
  "Web Development",
  "Mobile App development",
  "Website Design Figma",
  "Mobile App Design",
  "Graphic Design",
  "Website Hosting",
  "WhatsApp Business API",
  "ZOHO",
  "Email Marketing",
  "Amazon Marketing",
  "E-commerce Marketplace",
  "Events",
  "SMS Marketing",
] as const;

// Comprehensive Mega Services Category Map (from User Layout Request)
export const MEGA_SERVICES = {
  "Digital Marketing": [
    "Search Engine Optimization (SEO)",
    "Social Media Marketing",
    "Influencer Marketing",
    "PR & Outreach",
    "Email Marketing",
    "Amazon Marketing",
    "E-Commerce Marketplace",
    "SMS Marketing"
  ],
  "Web & App Development": [
    "Web Development",
    "Mobile App Development",
    "Website Hosting",
    "WhatsApp Business API",
    "ZOHO"
  ],
  "Design Agency": [
    "Website Design Figma",
    "Mobile App Design",
    "Graphic Design",
    "Branding"
  ],
  "Advertising & Paid Media": [
    "Google Ads",
    "Facebook Ads",
    "Instagram Ads",
    "Snapchat Ads",
    "X Ads",
    "Reddit Ads",
    "Pinterest Ads",
    "Linkedin Ads",
    "TikTok Ads",
    "Youtube Ads"
  ],
  "Lead Generation": [
    "LinkedIn",
    "Hospital",
    "Beauty And Wellness Center",
    "Medical Clinics",
    "Hotels",
    "Restaurants And Bars",
    "B2B Companies",
    "Real Estate",
    "School And Colleges",
    "Skills And Training Center",
    "Insurance Industries",
    "Fintech",
    "IT Industries",
    "Security Industries"
  ],
  "Video Production": [
    "Corporate Video Production",
    "3D Video Production",
    "SaaS Explainer Video Production",
    "Financial Video Production",
    "Social Video Production",
    "Motion Graphic Videos"
  ],
  "Explainer Video Production": [
    "Corporate Explainer Videos",
    "B2B Explainer Videos",
    "Tech Explainer Videos"
  ],
  "Animated Videos": [
    "3D Animated CGI",
    "Product Videos",
    "2D Animated Videos"
  ],
  "Events": [
    "Exhibition Stand"
  ]
} as const;

// Case Studies Data
export const CASE_STUDIES: CaseStudy[] = [
  {
    id: "1",
    title: "E-Commerce Transformation",
    client: "Luxury Fashion Brand",
    thumbnail: {
      src: "/images/case-studies/fashion-ecommerce.png",
      alt: "Fashion e-commerce website",
      width: 800,
      height: 600,
    },
    challenge: "A Dubai-based luxury fashion brand was struggling with low online sales and poor mobile experience. Their existing website had slow load times and complicated checkout process.",
    solution: "We rebuilt their e-commerce platform using Next.js 15 with server-side rendering, implemented progressive web app features, and optimized the checkout flow. Added Arabic language support and integrated local payment gateways.",
    results: "300% increase in mobile conversions, 65% faster page load times, 45% increase in average order value, and successful expansion to Saudi Arabia market.",
    tags: ["Web Development", "E-commerce"],
    year: 2024,
    featured: true,
  },
  {
    id: "2",
    title: "AI Customer Support Revolution",
    client: "Telecom Company",
    thumbnail: {
      src: "/images/case-studies/telecom-ai.png",
      alt: "AI chatbot interface",
      width: 800,
      height: 600,
    },
    challenge: "A major telecom company in UAE was facing high customer support costs and long wait times. Their support team was overwhelmed with repetitive inquiries.",
    solution: "Implemented an AI-powered chatbot using OpenAI GPT that handles 80% of customer inquiries automatically. Integrated with their CRM system and trained on their product knowledge base.",
    results: "70% reduction in support costs, 90% customer satisfaction with bot interactions, 24/7 support availability, and human agents now focus on complex issues only.",
    tags: ["AI & Automation", "Digital Marketing"],
    year: 2024,
    featured: true,
  },
  {
    id: "3",
    title: "Brand Identity Launch",
    client: "FinTech Startup",
    thumbnail: {
      src: "/images/case-studies/fintech-brand.png",
      alt: "Brand identity design",
      width: 800,
      height: 600,
    },
    challenge: "A new fintech startup needed a complete brand identity that would build trust in the competitive financial sector while appealing to a younger, tech-savvy audience.",
    solution: "Created a modern brand identity with a focus on trust, innovation, and accessibility. Designed logo, color system, typography, and comprehensive brand guidelines. Applied across all touchpoints.",
    results: "Successful launch with 40% brand recall within 3 months, $5M seed funding raised, featured in major tech publications, and social media following grew to 50K+.",
    tags: ["Brand Identity", "Digital Marketing"],
    year: 2023,
  },
  {
    id: "4",
    title: "SEO Domination Strategy",
    client: "Real Estate Portal",
    thumbnail: {
      src: "/images/case-studies/real-estate-seo.png",
      alt: "SEO analytics dashboard",
      width: 800,
      height: 600,
    },
    challenge: "A real estate portal was losing market share to competitors and had very low organic visibility. Their target keywords were dominated by established players.",
    solution: "Implemented comprehensive SEO strategy including technical fixes, content optimization, link building campaign, and local SEO focus. Created city-specific landing pages and optimized for featured snippets.",
    results: "500% increase in organic traffic, 150+ first page rankings, 60% increase in qualified leads, and 35% reduction in customer acquisition cost.",
    tags: ["SEO", "Web Development"],
    year: 2024,
  },
] as const;

// Team Members Data
export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    name: "Sarah Al-Hassan",
    role: "Founder & CEO",
    bio: "Visionary leader with 15+ years in digital marketing and technology. Previously led marketing at Fortune 500 companies across MENA region.",
    headshot: {
      src: "/images/team/sarah.png",
      alt: "Sarah Al-Hassan",
      width: 400,
      height: 400,
    },
    socialLinks: [
      { platform: "linkedin", url: "https://linkedin.com/in/sarah", icon: "linkedin" },
      { platform: "twitter", url: "https://twitter.com/sarah", icon: "twitter" },
    ],
    order: 1,
  },
  {
    id: "2",
    name: "Ahmed Khalil",
    role: "CTO",
    bio: "Full-stack architect and AI specialist. Former engineer at Google with expertise in scalable systems and machine learning integration.",
    headshot: {
      src: "/images/team/ahmed.png",
      alt: "Ahmed Khalil",
      width: 400,
      height: 400,
    },
    socialLinks: [
      { platform: "linkedin", url: "https://linkedin.com/in/ahmed", icon: "linkedin" },
      { platform: "github", url: "https://github.com/ahmed", icon: "github" },
    ],
    order: 2,
  },
  {
    id: "3",
    name: "Layla Rahman",
    role: "Creative Director",
    bio: "Award-winning designer with portfolio spanning luxury brands, tech startups, and everything in between. Passionate about meaningful design.",
    headshot: {
      src: "/images/team/layla.png",
      alt: "Layla Rahman",
      width: 400,
      height: 400,
    },
    socialLinks: [
      { platform: "linkedin", url: "https://linkedin.com/in/layla", icon: "linkedin" },
      { platform: "dribbble", url: "https://dribbble.com/layla", icon: "dribbble" },
      { platform: "behance", url: "https://behance.net/layla", icon: "behance" },
    ],
    order: 3,
  },
  {
    id: "4",
    name: "Omar Farooq",
    role: "Head of Growth",
    bio: "Data-driven marketer who has scaled startups from 0 to millions in revenue. Expert in performance marketing and conversion optimization.",
    headshot: {
      src: "/images/team/omar.png",
      alt: "Omar Farooq",
      width: 400,
      height: 400,
    },
    socialLinks: [
      { platform: "linkedin", url: "https://linkedin.com/in/omar", icon: "linkedin" },
      { platform: "twitter", url: "https://twitter.com/omar", icon: "twitter" },
    ],
    order: 4,
  },
] as const;

// Client Logos (placeholders with company names for text-based display)
export const CLIENT_LOGOS: ClientLogo[] = [
  { name: "TechVentures", src: "", alt: "TechVentures logo", href: "#" },
  { name: "InnovateCorp", src: "", alt: "InnovateCorp logo", href: "#" },
  { name: "GlobalReach", src: "", alt: "GlobalReach logo", href: "#" },
  { name: "DigitalEdge", src: "", alt: "DigitalEdge logo", href: "#" },
  { name: "FutureScale", src: "", alt: "FutureScale logo", href: "#" },
  { name: "PrimeDigital", src: "", alt: "PrimeDigital logo", href: "#" },
  { name: "NexaGrowth", src: "", alt: "NexaGrowth logo", href: "#" },
  { name: "ApexMedia", src: "", alt: "ApexMedia logo", href: "#" },
] as const;

// Testimonials data
export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "NextLevel transformed our digital presence completely. Their AI chatbot solution reduced our response time by 80% and increased customer satisfaction scores significantly.",
    name: "Sarah Al-Mansoori",
    role: "CEO",
    company: "TechVentures UAE",
  },
  {
    quote: "The web development team delivered a stunning e-commerce platform that exceeded our expectations. Sales have increased by 150% since launch. Truly exceptional work!",
    name: "Ahmed Hassan",
    role: "Marketing Director",
    company: "Global Retail Group",
  },
  {
    quote: "Their digital marketing expertise helped us reach new markets across the GCC region. ROI on our campaigns has been outstanding. Highly recommend their services.",
    name: "Fatima Rahman",
    role: "Founder",
    company: "Style Collective",
  },
  {
    quote: "Professional, creative, and results-driven. The branding work NextLevel did for us perfectly captures our vision and resonates with our target audience.",
    name: "Omar Khalil",
    role: "Operations Manager",
    company: "Prime Estates",
  },
];

// Service Interest Options for Contact Form
export const SERVICE_INTEREST_OPTIONS = [
  { value: "ai-chatbots", label: "AI Chatbots" },
  { value: "web-dev", label: "Web Development" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "graphic-design", label: "Graphic Design" },
  { value: "seo", label: "SEO Services" },
] as const;

// Budget Range Options for Contact Form
export const BUDGET_RANGE_OPTIONS = [
  { value: "<5k", label: "Less than $5,000" },
  { value: "5k-10k", label: "$5,000 - $10,000" },
  { value: "10k-25k", label: "$10,000 - $25,000" },
  { value: "25k-50k", label: "$25,000 - $50,000" },
  { value: "50k+", label: "$50,000+" },
] as const;

// Hero Scene Configuration
export const HERO_SCENE_CONFIG = {
  rings: [
    { radius: 2, tube: 0.05, segments: 64, color: "#c9a227" }, // Gold
    { radius: 2.5, tube: 0.03, segments: 64, color: "#d4af37" }, // Lighter Gold
    { radius: 3, tube: 0.02, segments: 64, color: "#bf953f" }, // Bronze
  ],
  animationSpeed: 0.001, // Radians per frame
  floatingAmplitude: 0.5, // Vertical movement
  material: {
    metalness: 0.8,
    roughness: 0.2,
  },
} as const;
